config = {
    'exp_name' : 'Experiemntal Name',
    'epoch' : 200,
    'lr' : 1,
    'batch' : 64,
    'val_frequency' : 100,
    'test_only' : False,
    'resume' : '',
    'train_dataset' : 'Training Datasets',
    'test_dataset': 'Test Dataset',
    'schedule_frequency' : 10,
    'imageH' : 32,
    'imageW' : 256,
    'encoder' : 'resnet',
    'decoder' : 'transformer',
    'alpha_path' : './data/benchmark_new.txt',
    'stn': False,
    'constrain': False,
    'char_len' : 60,
}
