config = {
    'exp_name' : 'Experimental Name',
    'epoch' : 10000,
    'lr' : 1,
    'batch' : 64,
    'val_frequency' : 100,
    'test_only' : False,
    'resume' : '',
    'train_dataset' : '',
    'test_dataset': '',
    'schedule_frequency' : 10,
    'imageH' : 32,
    'imageW' : 256,
    'encoder' : 'resnet',
    'decoder' : 'transformer',
    'alpha_path' : './data/char_document_Chinese.txt',
    'radical_path': './data/radical_all_Chinese.txt',
    'decompose_path': './data/decompose.txt',
    'radical_model': 'Pre-trained CCR-CLIP model',
    'stn': False,
    'constrain': False,
    'char_len' : 60,
}
